# Generated by Django 4.2.7 on 2023-12-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('area', models.CharField(choices=[('sm', 'small'), ('md', 'middle'), ('lg', 'large')], max_length=2)),
                ('inService', models.BooleanField(default=True)),
            ],
        ),
    ]
