# Generated by Django 4.2.7 on 2023-12-19 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('P', 'وحدة'), ('W', 'وزن'), ('B', 'صندوق')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.SmallIntegerField(default=0)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qtyOnHand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'ItemInventory',
                'verbose_name_plural': 'ItemInventorys',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
